apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-pr
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: exoscale
        # The Github repository
        repo: sks-argocd
        # Reference to a Secret containing an access token. (optional)
        # tokenRef:
        #   secretName: github-token
        #   key: token
        # Labels is used to filter the PRs that you want to target. (optional)
        # labels:
        # - preview
  template:
    metadata:
      name: 'demo-{{ branch }}-{{ number }}'
    spec:
      source:
        repoURL: 'https://github.com/exoscale/sks-argocd.git'
        path: k8s/demo
        targetRevision: '{{ head_sha }}'
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: demo
