apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
spec:
  project: default
  source:
    repoURL: 'https://github.com/exoscale/sks-argocd.git'
    path: k8s/ingress
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated: {}
