apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: k8s-lego-star
    app.kubernetes.io/part-of: k8s-lego-star
    app.kubernetes.io/component: cronjob
  name: k8s-lego-star
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
